SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `settings` (
  `id_settings` int(11) NOT NULL COMMENT 'ID Настройки',
  `source` varchar(255) DEFAULT NULL COMMENT 'Ключ настройки',
  `code` text COMMENT 'Код настройки',
  `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'Удалено',
  `deleted_date` datetime DEFAULT NULL COMMENT 'Дата удаления',
  `creation_date` datetime DEFAULT NULL COMMENT 'Дата создания'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


ALTER TABLE `settings`
  ADD PRIMARY KEY (`id_settings`);


ALTER TABLE `settings`
  MODIFY `id_settings` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID Настройки';
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
